language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- coverage run -m pytest --flake8
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
env:
  global:
  - secure: f5/vF1xGa5rFssJLJ4AHxaszzb5VCiaoldIzEGLb5AREaP62gaLV0i2y+FiT3YGGC8xPxkV2XxvCxKUNU4CyqC/nKQnHELbmpMhk4R1iUc4JgV4qvBHbYPkfEVkifsA2glUleMK9Mk2dcEkwI8ZxAOnWxW16jbeeembuKIg9hRDjJtHi4mPJMXSeA7+hgs9mCt49+q+t5WtHcG22CiGxhSZqbVi+yKrjMCsK6mIMcRhwtQKOMwfFCiR8GMyoZnlo2cRrnXwNlwZapOa6bb9yM8JukdclzhV+bMFL9CuUkBHbohYjzvovIlb+WNL6yHMIt1C4IHlOgyxapkTTuXK39fVaUzYUCbtsCer5YfRsqbXs9vkFJXai7tuoQ6HUhq/OfRiLLtgygeHQTLEkiW5YhH4MzZGK5TrBgdBlZ63cxf8TogTSsOY+Wo+qjFc9MXhjIrkw3Cw5zriaB2WtOHum3qO9M8GDO6KIeSmg+q75AThVqqLj5TnkHTCM7zXA9jG9lnWMgDore5b13IOCYqkE+QM+tYQvfQSu1g8tJljnCtOH6vUx6cU1XUz1jUZEoX7b+54T68HpoIEBDY0oWItXMypclcXGq5FLQ7DIQ5iQMsuF1YqzQmAbPAy4q64CdTyEY8PnaVgz7QPiMx81i6oio0DI78EtgGhmmXL5xyvR+ww=
  - secure: RCVF6gfqkZrnH0DAZaJe8PXKIyPHbmaEfJRPD7dVXa3aPyN2RvAjq4Q/9BFayQgjFOvmdBRx0X4LJKZiJUghZw8hj7BLXG093a3caeUUsE8gRj/PmOcA5ex2v72hY2TFwZ9e6eA5zmtTytwPMZ+Jx6d+OuVuloKoUJ+LXo5BTuAjHZsrI0BU7DrEncgSOxvmp0fDT9RLYsOIkclDAgsOVd7CPFn4exhebIddtmbW8QWEEyeBdglG/Yf95xQn8VFr0pGn6KfuFXgBUeKUem1Ra4g8qKBA3I9vunmsHAU6bcK+pYjvMKglAXjdkO3slm46/1Q4iYtr2DZYyr+tPeV9fkdBn44W4rFVSKE2gKjD4j8foYYTNwnokS6KmJVYgRpRD9gvCw+KXvKzEm5ThfSw0BdByHN2fzORK+hyckG5DmoN8JbL21ziw4rmM09Vj1OpvcqHaC2POK1G3FnyuMJCjvPZeX0WXEZscfWHJfhjAzPqeDIRYJhPNX5zTSRAHAORoU1g/qNvi1cTgAJlc8yxrlFl1QWDkGaKxiX214kEOJac7yDVajYk1ld9KCCoFnrMuwSHWKFHp31upQiC9Cq9iHU6/J0gy1/uz2gzDqHxnQHKOCK30JhdMkjufJ9+jBNmCy5z2uInIqv7Uss/aW9APCzWbsyxeXrCSJO1FzEcp9U=
