language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- coverage run -m pytest --flake8
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
env:
  global:
  - secure: X2/J8iyB5ueu+OuPK+Wpb/QeyxghFxDD2PDj0bhBIcQ4ao5LmSbhCeaMHtOwX/+cyfOyCwylit6F+S2D5Na+mUcEPs83GsoftgjQLl7v4d8NqXIL3eP4NdRRalrNCJmE0S4qYUfUB87F8uNRPehrEFGqT03ZevHR9XDVb2Tc7NsVWOCO22yXu+C6gd5pjeXoCztBzIEiO74rFamTe60SF1LRabLrn30gpCis0Usdgqv5iAtjo9qIjkUeVsoT8Fx2YM73K9fJ/S4NX4Ow6SGfOT5M53Sh2xek3NUegNa68ZRKTA0S3rN1nDb2QH9dbrEtgITdwShQrvtjIiNOYmeKb5O1Kgfp52lZqsnmmZPij1E/hzZ48ONOtrMGDGJWD8KVWnhrkrBYmqj+g/Z04oZ5oCkuMJhWzPSmpwMhY/vfRgpaMB78sXT5G0MgSs55O8PTGQS+DYeaWbk//bU+sNGG96GjWvOffI8jdz9Dic38y5kH0lQgDXyk4RHnYufNQu8sNohX2Uu5Xtvm+2SYd753FHuYqPhz0sKJzk+xmZEsrcuwy9JfVuWfUpZ4X9Oyjoblg+DAgcwBYNqw+XW9Btfc+Kk8C95pFdBZhPW/Ie6pZKpZmbeMA+LQLzBN7RAMJOwHAubeh5NULHQOE6uDNsCLUqBpBou81WtJtwTQBm0yH7o=
  - secure: EmgJbVYLXFTBe/Ic6Qieh1bvybcurghzCvneQKTZiBqb6LSLm0XJ0bcEXgbGbSP7MdsO30NEwetQKmePYCw9ai8BDKxcCW8swWX+WyGqqm87AqZq/VsLd7HvCzWXs+8H0qo8EStngWoQBa4A/0vjcdjcCx6VS/lQCNI85dLBcgRNcEyrygRy2Bf+nqvJq/+dre5zNM9IOWGwrhEWz/SBRjEeu/HvRXq3g/inJUPDyKZ6PpV2Y/IQdpnhIZc4Ca9t1L8UfX9xEflhCFiaS1hcuScIElPdcql97spC+7Es3+9+icvlgnFw1KSJPlKWItOcVGmlYJbzEbyE04ZX4TGZFhFzUWBhgs8RmSztzISDnWYxXcV8pYSiEPW/u5DOURcIweVPbRrYQaQU3LsvVy6HghWDf4nL9oPlxizHDpK5p7OK/R+06rE5UV7WUwMjh1ZhniDsHJrAjcDdzCzqxgEMIsaezcklvAFXriblpTbf+JUJ3ZWexbUIsV2UH6bdJMjOEDjGVYx0jofnNhh9X8PItN/VBErPEGHNyqjyVFudBjiCRkOZfFcB/fm7aBd3Gkvn95rQSiDJn5vdCSPUve4TbY3dhOSDfEKwsdUJMnUUVCYmhLM3bPRL7j62TZWGb6H6z0IJN+h+ygsrEoE6KEkMVLE7sOg1UN5YrVikkgcxYxI=